### ISSUE TITLE
Missing Dockerfile

### ISSUE THREAD

**Issue by nguyenhuedang** [tronscan/tronscan-api#10]
Hi @Rovak, I found that we could use docker-compose for build & running the app easier, however, it is lack of Dockerfile. Could you commit the Dockerfile to the repo?

**Comment by Rovak** [comment]
I will be creating a dockerfile soon

**Comment by Rovak** [comment]
Project can now be run using docker, see https://github.com/tronscan/tronscan-docker/tree/master/tronscan-api
