### ISSUE TITLE
Docker up fail

### ISSUE THREAD

**Issue by navcsdev** [tronscan/tronscan-api#17]
When I start by `docker-compose up` I get the error:

```
docker-compose up
Building tronscan
Step 1/4 : FROM gizmotronic/oracle-java:java8
 ---> b228dee7b72d
Step 2/4 : MAINTAINER Rovak
 ---> Using cache
 ---> 12032b940975
Step 3/4 : ADD ./target/universal/stage /opt/tronscan-api
ERROR: Service 'tronscan' failed to build: ADD failed: stat /var/lib/docker/tmp/docker-builder116826835/target/universal/stage: no such file or directory
```

**Comment by Rovak** [comment]
@navcsdev please try the docker containers at https://github.com/tronscan/tronscan-docker/tree/master/tronscan-api. The Dockerfile in this project is meant to build a new image which can be uploaded to dockerhub

**Comment by navcsdev** [comment]
@Rovak I got it. Thank you very much !
