### ISSUE TITLE
Returns data is inconsistent 

### ISSUE THREAD

**Issue by gutenye** [tronscan/tronscan-api#49]
Test with https://api.tronscan.org/api/transaction?address=TRAqdc9Un9JWqPMYSQR7o7EU5vUUG8tBR1&token=TRX&date_start=1539938562001&limit=100&sort=timestamp

- Most of the time, it returns  {"data":[]}, which is correct.
- Sometimes,  it returns with {"id":"", "contractData":null } with the old transactions before the date_start.

![ff085aea-555a-4418-9ca6-b30e19ab70fd](https://user-images.githubusercontent.com/377544/48059552-72da9e80-e1f4-11e8-9535-5eb8e5c27d1d.jpeg)

**Comment by roccomuso** [comment]
I think `date_start` is deprecated. I replaced it with `start_timestamp` and the results look good.
